CREATE TABLE note (
	id SERIAL PRIMARY KEY,
	title TEXT NOT NULL,
	tags TEXT[],
	file TEXT NOT NULL,
	created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE link (
	id SERIAL PRIMARY KEY,
	a_id INTEGER NOT NULL,
	b_id INTEGER NOT NULL,
	note TEXT
);
