CREATE TABLE note (
	id SERIAL PRIMARY KEY,
	title TEXT NOT NULL,
	tags TEXT[],
	file TEXT NOT NULL,
	created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE link (
	id SERIAL PRIMARY KEY,
	from_id INTEGER NOT NULL REFERENCES note(id),
	to_id INTEGER NOT NULL REFERENCES note(id),
	note TEXT
);
